name: growthbook_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  dio: ^4.0.6
  json_annotation: ^4.5.0
  tuple: ^2.0.0
  collection: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.11
  analyzer: ^4.6.0
  json_serializable: ^6.2.0
